apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: compositepostgresqlinstances.database.example.org
  annotations:
    uxp-guide: getting-started
spec:
  group: database.example.org
  names:
    kind: CompositePostgreSQLInstance
    plural: compositepostgresqlinstances
  claimNames:
    kind: PostgreSQLInstance
    plural: postgresqlinstances
  connectionSecretKeys:
    - username
    - password
    - endpoint
    - port
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  class:
                    type: string
                    enum: [small, medium, large]
                  storageGB:
                    type: integer
                  passwordSecretName:
                    type: string
                  region:
                    type: string
                    default: us-east-1
                  subnetIds:
                    items:
                      type: string
                    type: array
                  vpcId:
                    type: string
                required:
                  - storageGB
                  - passwordSecretName
            required:
              - parameters
          status:
            description: A Status represents the observed state
            properties:
              instance:
                description: Free-form field containing status information from an RDS Instance
                type: object
                x-kubernetes-preserve-unknown-fields: true
            type: object
