apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xpostgresqlinstances.azure.database.example.org
  labels:
    uxp-guide: getting-started
    provider: azure
spec:
  writeConnectionSecretsToNamespace: upbound-system
  compositeTypeRef:
    apiVersion: database.example.org/v1alpha1
    kind: CompositePostgreSQLInstance
  resources:
  - name: postgresqlserver
    base:
      apiVersion: dbforpostgresql.azure.upbound.io/v1beta1
      kind: Server
      spec:
        forProvider:
          version: "11"
          administratorLogin: psqladmin
          location: West US 2
          skuName: GP_Gen5_2
          storageMb: 5120
          sslEnforcementEnabled: true
          identity:
          - type: SystemAssigned
          # due to: https://github.com/Azure/azure-rest-api-specs/issues/9571
          infrastructureEncryptionEnabled: false
          administratorLoginPasswordSecretRef:
            key: password
            namespace: upbound-system
          resourceGroupNameSelector:
            matchControllerRef: true
    patches:
    - fromFieldPath: spec.parameters.class
      toFieldPath: spec.forProvider.skuName
      transforms:
      - type: map
        map:
          small: GP_Gen5_2
          medium: GP_Gen5_4
          large: MO_Gen5_4
    - fromFieldPath: metadata.name
      toFieldPath: metadata.name
      transforms:
        - type: string
          string:
            fmt: "%s-postgresql"
    - fromFieldPath: spec.claimRef.namespace
      toFieldPath: spec.writeConnectionSecretToRef.namespace
    - fromFieldPath: metadata.name
      toFieldPath: spec.writeConnectionSecretToRef.name
      transforms:
      - type: string
        string:
          fmt: "%s-postgresql"
    - fromFieldPath: spec.parameters.storageGB
      toFieldPath: spec.forProvider.storageMb
      transforms:
      - type: math
        math:
          multiply: 1024
    - fromFieldPath: spec.parameters.passwordSecretName
      toFieldPath: spec.forProvider.administratorLoginPasswordSecretRef.name
    connectionDetails:
        - fromConnectionSecretKey: username
        - fromConnectionSecretKey: password
        - fromConnectionSecretKey: endpoint
        - fromConnectionSecretKey: port
  - name: vnetrule
    base:
      apiVersion: dbforpostgresql.azure.upbound.io/v1beta1
      kind: VirtualNetworkRule
      spec:
        forProvider:
          resourceGroupNameSelector:
            matchControllerRef: true
          subnetIdSelector:
            matchControllerRef: true
          serverNameSelector:
            matchControllerRef: true
  - name: rg
    base:
      apiVersion: azure.upbound.io/v1beta1
      kind: ResourceGroup
      spec:
        forProvider:
          location: West US 2
  - name: vnet
    base:
      apiVersion: network.azure.upbound.io/v1beta1
      kind: VirtualNetwork
      spec:
        forProvider:
          resourceGroupNameSelector:
            matchControllerRef: true
          location: West US 2
          addressSpace:
           - 192.168.0.0/16
  - name: subnet
    base:
      apiVersion: network.azure.upbound.io/v1beta1
      kind: Subnet
      spec:
        forProvider:
          resourceGroupNameSelector:
            matchControllerRef: true
          virtualNetworkNameSelector:
            matchControllerRef: true
          addressPrefixes:
            - 192.168.1.0/24
          serviceEndpoints:
            - Microsoft.Sql
    patches:
    - type: ToCompositeFieldPath
      fromFieldPath: status.atProvider.addressPrefixes[0]
      toFieldPath: status.instance.subnet
  - name: firewallrule
    base:
      apiVersion: dbforpostgresql.azure.upbound.io/v1beta1
      kind: FirewallRule
      spec:
        forProvider:
          resourceGroupNameSelector:
            matchControllerRef: true
          serverNameSelector:
            matchControllerRef: true
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: status.instance.subnet
      toFieldPath: spec.forProvider.startIpAddress
      transforms:
      - type: string
        string:
          type: TrimSuffix
          trim: "0/24"
      - type: string
        string:
          fmt: "%s1" #192.168.1.1
    - type: FromCompositeFieldPath
      fromFieldPath: status.instance.subnet
      toFieldPath: spec.forProvider.endIpAddress
      transforms:
      - type: string
        string:
          type: TrimSuffix
          trim: "0/24"
      - type: string
        string:
          fmt: "%s2" #192.168.1.2
